### PR TITLE
EKS Blueprints GPU, Kubecost, Istio and Stateful patterns to CNOE

### PR DESCRIPTION
**Pull request by elamaran11**
This PR is to add following 4 patterns from EKS Terraform Blueprints to CNOE Backstage Integrations:
1. GPU NVDIA Pattern
2. Kubecost Pattern
3. Istio on EKS pattern
4. Stateful Workloads Pattern

### CODE REVIEW

**Comment by elamaran11** [comment]
@nimakaviani Pls review and merge this. Another EKS Blueprints pattern to backstage integration.

**Comment by nimakaviani** [comment]
thank you will test things and merge. Did it work successfully on your end? Did it deploy stuff as intended?

**Comment by elamaran11** [comment]
> thank you will test things and merge. Did it work successfully on your end? Did it deploy stuff as intended?

Yes it mostly worked well from my end except wait for a P5 which we never get. Otherwise i got all other resources spun up. Please run from your end.

**Comment by elamaran11** [comment]
Hi @nimakaviani Lets merge these 4 patterns and we need to find couple of folks who can test all 4 of these patterns and provide feedback to us so we can evolve faster. I will spend time to test this week but we can get some help to expedite.

**Pull request closed without merging**
